### ISSUE TITLE
 .lpos is not a function

### ISSUE THREAD

**Issue by imranaalam** [mmkal/handy-redis#258] opened 2020-12-08 13:17 UTC
i am trying this in express/ nodejs using
handyredis.addNodeRedisCommand('lpos')  
handyredis.createNodeRedisClient(Redisclient)  
console.log('handy redis connected  HANDY REDIS HANDY REDIS  HANDY REDIS  HANDY REDISH HANDY REDIS HANDY REDIS HANDY REDIS')

on calling lpos with handyredis client it says .lpos is not a function

**Comment by mmkal** [comment] 2020-12-08 14:55
I'm not able to repro this. Could you share a full code reproduction along with:

- which version of redis you have installed
- which version of handy-redis you have installed
- which version of `redis-commands` your lockfile resolved
- how you're initialising `Redisclient` above - it's a good idea to call `addNodeRedisCommand` as early as possible

Note that lpos is included in the latest `redis-commands` package, so you may be able to solve this problem just by updating the `redis` dependency (`npm install redis@latest`)

**Comment by mmkal** [comment] 2020-12-31 10:33
@imranaalam closing since there's not much more I can do here without the above info. Let me know if you are still seeing an issue.

**Closed by mmkal** 2020-12-31 10:33 UTC
